name: Build with PyInstaller

on:
  push:
    branches:
      - main  # Запускать workflow при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать workflow при создании pull request в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'  # Укажите нужную версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # Установите другие зависимости, если они есть
        # pip install -r req.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller main.spec

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/  # Путь к папке, где PyInstaller сохраняет скомпилированные файлы
